export const SEED_JOBS = [
  {
    _id: "66e01a111111111111111101",
    source: "manual-paste",
    companyName: "Stripe",
    companyLogoUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&h=128&fit=crop&q=80",
    role: "Senior Distributed Systems Engineer",
    jd: `<h3>About Stripe</h3><p>Stripe is a financial infrastructure platform for businesses. Millions of companies—from the world's largest enterprises to the most ambitious startups—use Stripe to accept payments, grow their revenue, and accelerate new business opportunities.</p><h3>What you'll do</h3><ul><li>Design, build, and operate globally distributed ledger services with 99.999% availability.</li><li>Collaborate with infrastructure and reliability teams to optimize cross-region replication latency.</li><li>Write clean, resilient code in Go and Ruby.</li></ul><h3>Requirements</h3><ul><li>5+ years building high-throughput distributed systems.</li><li>Deep understanding of consensus algorithms (Raft/Paxos) and relational database internals.</li><li>Strong background in concurrency, latency profiling, and network programming.</li></ul>`,
    salaryRange: { min: 185000, max: 245000, currency: "USD" },
    location: "San Francisco, CA (Hybrid)",
    pincode: "94103",
    experienceRequired: { min: 5, max: 10 },
    jobType: "hybrid",
    applyUrl: "https://stripe.com/jobs",
    applyMode: "easy-apply",
    skills: ["Go", "Distributed Systems", "PostgreSQL", "Kafka", "Kubernetes"],
    status: "published",
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    _id: "66e01a111111111111111102",
    source: "link",
    companyName: "Vercel",
    companyLogoUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&h=128&fit=crop&q=80",
    role: "Staff Frontend Architect",
    jd: `<h3>About Vercel</h3><p>Vercel's Frontend Cloud gives developers collaborative environments and edge infrastructure to build at the speed of inspiration.</p><h3>The Role</h3><p>We are seeking a Staff Frontend Architect to guide the next evolution of Next.js and frontend streaming protocols.</p><ul><li>Architect edge-rendered UI components and streaming SSR pipelines.</li><li>Author RFCs and contribute to open-source developer tooling.</li><li>Partner with design engineering to define accessible micro-interactions.</li></ul><h3>Qualifications</h3><ul><li>7+ years modern frontend development with deep mastery of React, Next.js, and TypeScript.</li><li>Proven track record of optimizing Core Web Vitals at massive scale.</li><li>Passion for developer ergonomics and API design.</li></ul>`,
    salaryRange: { min: 190000, max: 260000, currency: "USD" },
    location: "Remote (Global)",
    pincode: "",
    experienceRequired: { min: 6, max: 12 },
    jobType: "remote",
    applyUrl: "https://vercel.com/careers",
    applyMode: "easy-apply",
    skills: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Web Performance"],
    status: "published",
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    _id: "66e01a111111111111111103",
    source: "manual-paste",
    companyName: "Linear",
    companyLogoUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&h=128&fit=crop&q=80",
    role: "Full-Stack Product Engineer",
    jd: `<h3>Craft at Linear</h3><p>Linear is building the modern standard for software development. Our mission is to make work feel like play with tools that are fast, intuitive, and beautifully designed.</p><h3>Responsibilities</h3><ul><li>Develop real-time sync engines and offline-first local state caches.</li><li>Build lightning-fast keyboard-first interfaces in TypeScript.</li><li>Work across the stack from Node/GraphQL backend to polished React desktop/web clients.</li></ul><h3>Requirements</h3><ul><li>3+ years building product-focused web applications.</li><li>Obsession with speed, 60fps animations, and zero-latency feedback.</li><li>Experience with IndexedDB, WebSockets, or CRDTs is a big plus.</li></ul>`,
    salaryRange: { min: 150000, max: 200000, currency: "USD" },
    location: "Remote (US/EU)",
    pincode: "",
    experienceRequired: { min: 3, max: 7 },
    jobType: "remote",
    applyUrl: "https://linear.app/careers",
    applyMode: "easy-apply",
    skills: ["TypeScript", "React", "GraphQL", "Node.js", "WebSockets"],
    status: "published",
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    _id: "66e01a111111111111111104",
    source: "manual-paste",
    companyName: "Ramp",
    companyLogoUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&h=128&fit=crop&q=80",
    role: "Senior AI / ML Platform Engineer",
    jd: `<h3>About Ramp</h3><p>Ramp is the ultimate platform for modern finance. We help thousands of businesses save time and money with corporate cards, expense management, and AI invoice automation.</p><h3>What you'll work on</h3><ul><li>Deploy low-latency LLM inference pipelines for real-time receipt parsing and fraud detection.</li><li>Build evaluation harnesses for multi-model AI routing with Groq, Anthropic, and OpenAI.</li><li>Scale vector embeddings and semantic search infrastructure in Python and Rust.</li></ul><h3>Qualifications</h3><ul><li>4+ years engineering backend or ML systems in production.</li><li>Expertise in Python, PyTorch, LangChain, or direct LLM SDK implementations.</li><li>Experience scaling Postgres or vector databases (Pinecone/pgvector).</li></ul>`,
    salaryRange: { min: 175000, max: 230000, currency: "USD" },
    location: "New York, NY (Onsite)",
    pincode: "10003",
    experienceRequired: { min: 4, max: 9 },
    jobType: "onsite",
    applyUrl: "https://ramp.com/careers",
    applyMode: "easy-apply",
    skills: ["Python", "Machine Learning", "FastAPI", "PostgreSQL", "Docker", "PyTorch"],
    status: "published",
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    _id: "66e01a111111111111111105",
    source: "link",
    companyName: "Supabase",
    companyLogoUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&h=128&fit=crop&q=80",
    role: "Database Reliability Engineer",
    jd: `<h3>About Supabase</h3><p>Supabase is an open source Firebase alternative providing Postgres databases, authentication, real-time subscriptions, and storage.</p><h3>The Role</h3><ul><li>Automate multi-tenant PostgreSQL provisioning, failover, and point-in-time recovery.</li><li>Diagnose performance bottlenecks, query locks, and memory contention across 500,000+ databases.</li><li>Contribute upstream extensions and patches to the PostgreSQL community.</li></ul>`,
    salaryRange: { min: 140000, max: 195000, currency: "USD" },
    location: "Remote",
    pincode: "",
    experienceRequired: { min: 4, max: 8 },
    jobType: "remote",
    applyUrl: "https://supabase.com/careers",
    applyMode: "external",
    skills: ["PostgreSQL", "Linux", "Docker", "Go", "Database Internals"],
    status: "published",
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    _id: "66e01a111111111111111106",
    source: "manual-paste",
    companyName: "Scale AI",
    companyLogoUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&h=128&fit=crop&q=80",
    role: "Lead Cloud Infrastructure Engineer",
    jd: `<h3>About Scale</h3><p>Scale accelerates AI development by providing the foundation data layer for frontier models.</p><h3>Responsibilities</h3><ul><li>Manage multi-cluster Kubernetes environments across AWS and GCP.</li><li>Implement zero-trust security architecture, IAM least-privilege, and automated Terraform workflows.</li><li>Scale observability stack (Prometheus, Grafana, OpenTelemetry) ingestion to terabytes/day.</li></ul>`,
    salaryRange: { min: 170000, max: 220000, currency: "USD" },
    location: "San Francisco, CA",
    pincode: "94105",
    experienceRequired: { min: 5, max: 9 },
    jobType: "hybrid",
    applyUrl: "https://scale.com/careers",
    applyMode: "easy-apply",
    skills: ["Kubernetes", "AWS", "Terraform", "Docker", "Python", "CI/CD"],
    status: "published",
    postedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  }
];

export const SEED_MCQS = [
  {
    _id: "66e02b111111111111111101",
    category: "dsa",
    difficulty: "medium",
    question: "In a min-heap with N elements, what is the worst-case time complexity of inserting a new element?",
    options: [
      "O(1)",
      "O(log N)",
      "O(N)",
      "O(N log N)"
    ],
    correctIndex: 1,
    explanation: "Inserting an element adds it to the leaf level and requires 'bubbling up' along the height of the tree. Since a binary heap has a height of floor(log2(N)), the worst-case time complexity is O(log N)."
  },
  {
    _id: "66e02b111111111111111102",
    category: "dsa",
    difficulty: "hard",
    question: "Which data structure allows both O(1) average lookup and O(1) deletion while maintaining insertion-order iteration?",
    options: [
      "Standard Binary Search Tree",
      "Hash Map + Doubly Linked List (LinkedHashMap / LRU Cache structure)",
      "Red-Black Balanced Tree",
      "Skip List with Fibonacci Pointers"
    ],
    correctIndex: 1,
    explanation: "Combining a Hash Map with a Doubly Linked List allows O(1) key lookups via hashing and O(1) node detachment/re-linking for updates and removals while tracking insertion/access order."
  },
  {
    _id: "66e02b111111111111111103",
    category: "aptitude",
    difficulty: "medium",
    question: "A microservice cluster processes 1,200 requests/second with an average latency of 50 milliseconds. By Little's Law (L = λW), what is the average number of concurrent requests in flight?",
    options: [
      "60 concurrent requests",
      "240 concurrent requests",
      "600 concurrent requests",
      "12,000 concurrent requests"
    ],
    correctIndex: 0,
    explanation: "Little's Law states L = λ * W. Here arrival rate λ = 1,200 req/sec, and latency W = 0.050 seconds. Therefore, L = 1,200 * 0.050 = 60 concurrent requests in flight."
  },
  {
    _id: "66e02b111111111111111104",
    category: "dsa",
    difficulty: "easy",
    question: "What is the time complexity of detecting a cycle in a linked list using Floyd's Tortoise and Hare algorithm?",
    options: [
      "O(N) time and O(1) space",
      "O(N log N) time and O(N) space",
      "O(N^2) time and O(1) space",
      "O(1) time and O(N) space"
    ],
    correctIndex: 0,
    explanation: "Floyd's algorithm advances slow pointer by 1 and fast pointer by 2. If a cycle exists, they meet within at most 2 traversals of the loop, taking O(N) time with only two pointer variables (O(1) auxiliary space)."
  },
  {
    _id: "66e02b111111111111111105",
    category: "general",
    difficulty: "medium",
    question: "In distributed database design, what does the CAP theorem state is impossible to guarantee simultaneously in the presence of network partitions?",
    options: [
      "Consistency and Latency",
      "Consistency and Availability",
      "Durability and Partition Tolerance",
      "Atomicity and Scalability"
    ],
    correctIndex: 1,
    explanation: "According to Eric Brewer's CAP theorem, when a network partition (P) inevitably occurs in a distributed system, you must trade off between returning the latest consistent data (Consistency) and responding to every query immediately (Availability)."
  }
];

export const SEED_CANDIDATES = [
  {
    name: "Maya Lin",
    email: "maya.lin@example.com",
    role: "Senior Full-Stack Engineer",
    location: "San Francisco, CA",
    experienceYears: 6,
    skills: ["TypeScript", "React", "Next.js", "Node.js", "PostgreSQL", "AWS"],
    profileCompleteness: 95,
    streak: 14,
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=128&h=128&fit=crop&q=80",
    bio: "Ex-Stripe engineer focused on high-throughput backend APIs and modern Next.js design systems."
  },
  {
    name: "David Chen",
    email: "david.chen@example.com",
    role: "Staff Infrastructure / DevOps Engineer",
    location: "Remote, US",
    experienceYears: 8,
    skills: ["Kubernetes", "Go", "Docker", "Terraform", "AWS", "Distributed Systems"],
    profileCompleteness: 100,
    streak: 22,
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=128&h=128&fit=crop&q=80",
    bio: "Specializing in zero-downtime Kubernetes deployments, multi-region observability, and cloud cost optimization."
  },
  {
    name: "Priya Sharma",
    email: "priya.sharma@example.com",
    role: "Lead Frontend Engineer",
    location: "New York, NY",
    experienceYears: 5,
    skills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "GraphQL"],
    profileCompleteness: 90,
    streak: 9,
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=128&h=128&fit=crop&q=80",
    bio: "Passionate about 60fps micro-animations, accessible design systems, and edge SSR rendering."
  },
  {
    name: "Elena Rostova",
    email: "elena.rostova@example.com",
    role: "AI / Machine Learning Engineer",
    location: "Austin, TX",
    experienceYears: 4,
    skills: ["Python", "Machine Learning", "PyTorch", "FastAPI", "Docker", "MongoDB"],
    profileCompleteness: 88,
    streak: 18,
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=128&h=128&fit=crop&q=80",
    bio: "Building fine-tuned LLM inference engines and semantic search retrieval pipelines."
  }
];

